Name:     evtest
Version:  1.36
Release:  1
Summary:  Event device test program
Group:    System/Kernel and hardware
License:  GPLv2+
URL:      https://gitlab.freedesktop.org/libevdev/evtest/
Source0:  https://gitlab.freedesktop.org/libevdev/evtest/-/archive/%{name}-%{version}/%{name}-%{name}-%{version}.tar.bz2

BuildRequires:  automake
BuildRequires:  asciidoc
BuildRequires:  xmlto
BuildRequires:  pkgconfig(libxml-2.0)

%description
%{name} is a simple utility to query information about input
devices and watch the event stream generated by input devices.

%prep
%autosetup -n %{name}-%{name}-%{version}
autoreconf -fi

%build
%configure
%make_build

%install
%make_install

%files
%doc README.md
%license COPYING
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*
